import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { SessionProvider } from "next-auth/react";
import { LanguageProvider } from "../contexts/LanguageContext";
import ErrorBoundary from "../components/ErrorBoundary";

import "./globals.css";
// Jika ini menyebabkan error build, ganti jadi <link> di <head> (lihat catatan di bawah)


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Undangan Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id" data-bs-theme-mode="system">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css"
        />
        {/* Bootstrapper theme HARUS dieksekusi SEBELUM CSS/JS Metronic dipakai */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function(){
  var defaultThemeMode = "light";
  var themeMode;
  if (document.documentElement) {
    if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
      themeMode = document.documentElement.getAttribute("data-bs-theme-mode");
    } else {
      if (localStorage.getItem("data-bs-theme") !== null) {
        themeMode = localStorage.getItem("data-bs-theme");
      } else {
        themeMode = defaultThemeMode;
      }
    }
    if (themeMode === "system") {
      themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
    }
    document.documentElement.setAttribute("data-bs-theme", themeMode);
  }
})();
            `,
          }}
        />
        {/* Jika import CSS dari /public via import TS bermasalah, gunakan <link>:
        <link rel="stylesheet" href="/metronic/assets/plugins/global/plugins.bundle.css" />
        <link rel="stylesheet" href="/metronic/assets/css/style.bundle.css" />
        */}
      </head>
      <body id="kt_body" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"
          strategy="beforeInteractive"
        />
        <ErrorBoundary>
          <SessionProvider>
            <LanguageProvider>{children}</LanguageProvider>
          </SessionProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
